name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/nuii/nuii-fe

            git fetch --all
            git reset --hard origin/main
            git clean -fd

            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            export PATH="$HOME/.bun/bin:$PATH"

            bun install
            bun run build

            pm2 reload nuii-fe --update-env

      - name: Notify Success
        if: success()
        run: echo "🚀 Deployment was successful"
