name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug SSH Variables
        run: |
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          # Jangan print SSH_PRIVATE_KEY karena sensitif!

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 178.16.137.201
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/nuii-ai
            git stash
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            bun install
            bun run build
            pm2 restart nuii-ai
